/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caculator;

// import org.junit.Test;
import org.testng.Assert;

import org.testng.annotations.Test;

public class AppTest {
    @Test 
    public void testAdd1() {
        App classUnderTest = new App();
        Assert.assertEquals(classUnderTest.add(1, 2), 3);
    }

    @Test
    public void testAdd2() {
        App classUnderTest = new App();
        Assert.assertEquals(classUnderTest.add(0, 5), 5);
    }

    @Test
    public void testAdd3() {
        App classUnderTest = new App();
        Assert.assertEquals(classUnderTest.add(1, 0), 2);
    }
}


