/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caculator;

public class App {
    public int add(int a, int b) {
        return a + b;
    }

    public int sub(int a, int b) {
        return a - b;
    }

    public static void main(String[] args) {
        System.out.println(new App().add(1, 2));
    }
}
